app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from hashlib import md5

followers = db.Table(
    "followers",
    db.Column("follower_id", db.Integer, db.ForeignKey("user.id")),
    db.Column("followed_id", db.Integer, db.ForeignKey("user.id")),
)


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    posts = db.relationship("Post", backref="author", lazy="dynamic")
    followed = db.relationship(
        "User",
        secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref("followers", lazy="dynamic"),
        lazy="dynamic",
    )

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?s={size}&d=identicon'

    def followed_posts(self):
        followed = Post.query.join(followers, (followers.c.followed_id == Post.user_id)).filter(followers.c.follower_id == self.id)
        users_posts = Post.query.filter_by(user_id=self.id)
        return followed.union(users_posts).order_by(Post.created_on.desc())

    def __repr__(self):
        return f"User: {self.name}"

    def generate_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, pw_to_check):
        return check_password_hash(self.password, pw_to_check)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(
            followers.c.followed_id == user.id
            ).count() > 0


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    body = db.Column(db.Text)
    created_on = db.Column(db.DateTime, index=True, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        return f"<Post: {self.body[:30]}...>"


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
# Initialize Flask app
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)

    login_manager.init_app(app)
    login_manager.login_view = 'account.login'
    login_manager.login_message_category = 'warning'

    moment.init_app(app)

    from app.blueprints.account import account
    app.register_blueprint(account, url_prefix='/account')

    from app.blueprints.users import users
    app.register_blueprint(users, url_prefix='/users')


    with app.app_context():
        from app import routes
        
        from app.blueprints.errors import errors
        app.register_blueprint(errors, url_prefix='/error')

    # email error logging
    if not app.debug:
        server = app.config.get('MAIL_SERVER')
        username = app.config.get('MAIL_USERNAME')
        password = app.config.get('MAIL_PASSWORD')
        use_tls = app.config.get('MAIL_USE_TLS')
        admins = app.config.get('ADMIN_EMAIL')

    return app

from app import models

app/blueprints/account/routes.py
from . import account
from flask import request, render_template, redirect, url_for, flash
from flask_login import login_required, login_user, logout_user, current_user
from app.models import User
from app import db


@account.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        remember_me = request.form.get("remember_me")

        user = User.query.filter_by(email=email).first()
        if user:
            if user.check_password(password):
                login_user(user, remember=remember_me)
                flash("Login accepted", "success")
                return redirect(url_for("index"))
        flash("Invalid user / pass combination", "warning")
        return render_template("login.html")

    return render_template("login.html")


@account.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        name = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        confirm_password = request.form.get("confirm_password")

        if User.query.filter_by(email=email).first():
            flash("That email is already in use.", "danger")
            return redirect(url_for("account.register"))

        if password != confirm_password:
            flash("Password and confirmation must be the same.", "danger")
            return redirect(url_for("account.register"))
        u = User(name=name, email=email, password=password)
        u.generate_password(u.password)

        db.session.add(u)
        db.session.commit()
        flash("User registration successful.", "success")
        return redirect(url_for("account.login"))
    return render_template("register.html")


@account.route("/logout", methods=["GET"])
def logout():
    logout_user()
    flash("Logged out successfully", "info")
    return redirect(url_for("account.login"))

app/blueprints/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from . import routes

app/blueprints/users/routes.py
from . import users as app
from flask import flash, redirect, url_for, render_template
from flask_login import login_required, current_user
from app import db
from app.models import User

@app.route("/")
@login_required
def index():
    if not current_user or current_user.is_anonymous:
        flash('You do have to access to this page. Please login before continuing.', 'info')
        return redirect(url_for('account.login'))
    users = [i for i in User.query.all() if i.id != current_user.id]
    return render_template("users.html", users=users)


@app.route("/users/follow/<int:id>")
def user_follow(id):
    user = User.query.get(id)
    current_user.follow(user)
    db.session.commit()
    flash(f"You have followed {user.name}", "success")
    return redirect(url_for("users.index"))


@app.route("/users/unfollow/<int:id>")
def user_unfollow(id):
    user = User.query.get(id)
    current_user.unfollow(user)
    db.session.commit()
    flash(f"You have unfollowed {user.name}", "success")
    return redirect(url_for("users.index"))

app/routes.py
from app import db, login_manager
from app.models import User, Post
from flask import render_template, request, redirect, url_for, flash, current_app as app
from flask_login import login_user, logout_user, current_user, login_required


@app.route("/", methods=["GET", "POST"])
def index():
    if current_user.is_authenticated:
        posts = current_user.followed_posts()
    else:
        posts = Post.query.order_by(Post.created_on).all()
    
    if request.method == "POST":
        post_body = request.form.get("post_body")
        p = Post(body=post_body, user_id=current_user.id)
        db.session.add(p)
        db.session.commit()
        flash("Post created.", "success")
        return redirect(url_for("index"))

    return render_template("index.html", posts=posts)


@app.route("/profile")
@login_required
def profile():
    posts = User.query.get(current_user.id).posts.all()
    return render_template("profile.html", posts=posts)


@app.route("/profile/post/<int:id>")
def profile_single(id):
    p = Post.query.get(id)
    post = p
    return render_template("profile-single.html", post=post)


@app.route("/post/<int:id>")
def index_single(id):
    post = Post.query.get(id)
    return render_template("index-single.html", post=post)

app/templates/index-single.html
{% extends 'layout.html' %}

{% block title %}Post | {{ super() }}{% endblock %}

{% block content %}
<h1>Post page</h1>
<hr>

<a href="{{ url_for('index') }}">Go Back</a>

<ul class="list-group">
  <li class="list-group-item">
    <small>Posted: {{ moment(post.created_on).fromNow() }}</small>
    <div>{{ post.body }}</div>
  </li>
</ul>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}

{% block title %}Home | {{ super() }}{% endblock %}

{% block content %}
      <h1>Home page</h1>
      <hr>

      <div class="jumbotron jumbotron-fluid">
            <div class="container">
                  <h1 class="display-3">Welcome to Flask Blog</h1>
                  <p class="lead">Where we learn to code</p>
                  <hr class="my-2">
                  <p>More info</p>
                  <p class="lead">
                        <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Don't click this button</a>
                  </p>
            </div>
      </div>

      {% if current_user.is_authenticated %}
            <h4>Hello, {{ current_user.name }}</h4>
      {% else %}
            <h4>Please Log in.</h4>
      {% endif %}

      <form class="form-inline" action="{{ url_for('index') }}" method="POST">
            <div class="form-group">
                  <input type="text" name="post_body" class="form-control" placeholder="Type your status here.">
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
      </form>

      <ul class="list-group">
            {% for post in posts %}
                  <li class="list-group-item">
                        <div class="row">
                              <div class="col-md-1">
                                    <img src="{{ post.author.avatar(128) }}" class="img-fluid" alt="">
                              </div>
                              <div class="col-md">
                                    <div>
                                          <a href="{{ url_for('index_single', id=post.id) }}">{{ post.body }}</a>
                                     </div>
                                     <cite>{{ post.author.name }}</cite>
                                     <br>
                                     <!-- <small>{{ post.created_on.strftime('%B %d, %Y @ %I:%M %p') }}</small> -->
                                     <small>{{ moment(post.created_on).fromNow() }}</small>
                              </div>
                        </div>
                  </li>
            {% endfor %}
      </ul>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>
    {% block title %}Flask Blog{% endblock %}
  </title>

</head>

<body>
  <header>
    {% include './partials/nav.html' %}
  </header>

  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message }}</strong> 
          </div>
        {% endfor %}
    {% endif %}
  {% endwith %}

  <main class="container">
    {% block content %}{% endblock %}
  </main>
  
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  {{ moment.include_moment() }}
</body>

</html>

app/templates/login.html
{% extends 'layout.html' %}

{% block title %}Login | {{ super() }}{% endblock %}

{% block content %}
<h1>Login</h1>
<hr>
<div class="row">
  <div class="col-md-4">
    <form action="{{ url_for('account.login') }}" method="POST">
      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" name="email" id="email" placeholder="email">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="password">
      </div>
      <div class="form-check">
        <label class="form-check-label">
          <input type="checkbox" class="form-check-input" name="remember_me" id="remember_me" value="True">
          Remember Me
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock %}
    

app/templates/partials/nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <a class="navbar-brand" href="{{url_for('index') }}">Navbar</a>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
    aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('index') }}">Home</a>
      </li>
      {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('profile') }}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.index') }}">Users</a>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav m1-auto">
      {% if not current_user.is_authenticated %}
        <li class="nav-item">
          <a href="{{ url_for('account.login') }}" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for('account.register') }}" class="nav-link">Register</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{{ url_for('account.logout') }}" class="nav-link">Logout</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/profile-single.html
{% extends 'layout.html' %}

{% block title %}Post | {{ super() }}{% endblock %}

{% block content %}
<h1>Profile page</h1>
<hr>

<a href="{{ url_for('profile') }}">Go Back</a>

<ul class="list-group">
  <li class="list-group-item">
    <small>Posted: {{ moment(post.created_on).fromNow() }}</small>
    <div>{{ post.body }}</div>
  </li>
</ul>
{% endblock %}

app/templates/profile.html
{% extends 'layout.html' %}

{% block title %}Profile | {{ super() }}{% endblock %}

{% block content %}
<h1>Profile page</h1>
<hr>
<ul class="list-group">
    {% for post in posts %}
    <li class="list-group-item">
        <div class="row">
            <div class="col-md-1">
                <img src="{{ post.author.avatar(128) }}" class="img-fluid" alt="">
            </div>
            <div class="col-md">
                <div><a href="{{ url_for('profile_single', id=post.id) }}">{{ post.body }}</a></div>
                <small>{{ moment(post.created_on).fromNow() }}</small>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/register.html
{% extends 'layout.html' %}

{% block title %}Register | {{ super() }}{% endblock %}

{% block content %}
<h1>Register page</h1>
<hr>
<div class="row">
  <div class="col-md-4">
    <form action="{{ url_for('account.register') }}" method="POST">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" name="username" id="username" placeholder="Username">
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" name="email" id="email" placeholder="email">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="password">
      </div>
      <div class="form-group">
        <label for="confirm_password">Confirm Password</label>
        <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

{% endblock %}

app/templates/users.html
{% extends 'layout.html' %}

{% block title %}Users | {{ super() }}{% endblock %}

{% block content %}
<h1>Users List</h1>
<hr>

<a href="{{ url_for('index') }}">Go Back</a>

<ul class="list-group">
    {% for user in users %}
        <li class="list-group-item">
            <div>
                <img class="img-fluid" src="{{ user.avatar(64) }}" alt=""> {{ user.email }}
                {% if not current_user.is_following(user) %}
                <span>
                    <a class="btn btn-success" href="{{ url_for('users.user_follow', id=user.id) }}">Follow</a>
                </span>
                {% else %}
                <span>
                    <a class="btn btn-warning" href="{{ url_for('users.user_unfollow', id=user.id) }}">Unfollow</a>
                </span>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>
{% endblock %}